services:
  selenium-chrome:
    image: selenium/standalone-chrome:123.0
    ports:
      - 4444:4444
    environment:
      SE_NODE_MAX_SESSIONS: 5
    network_mode: host

  waste-organisations-mock-api:
    build:
      context: ./lib/epr-frontend-journey-tests
      dockerfile: docker/mock/Dockerfile
    ports:
      - '3020:3020'
    environment:
      NODE_ENV: development
    networks:
      - cdp-tenant

  localstack:
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./lib/epr-backend-journey-tests/docker/scripts/localstack:/etc/localstack/init/ready.d

  epr-backend:
    profiles: ['all', 'epr-backend']
    environment:
      ADMIN_UI_ENTRA_CLIENT_ID: ${ENTRA_CLIENT_ID:-clientId}
      APP_BASE_URL: http://epr-backend:3001
      AUDIT_ENABLED: true
      CDP_UPLOADER_URL: http://cdp-uploader:7337
      DEFRA_ID_OIDC_WELL_KNOWN_URL: ${DEFRA_ID_OIDC_WELL_KNOWN_URL:-http://defra-id-stub:3200/cdp-defra-id-stub/.well-known/openid-configuration}
      ENTRA_OIDC_WELL_KNOWN_CONFIGURATION_URL: ${ENTRA_OIDC_WELL_KNOWN_CONFIGURATION_URL:-http://entra-stub:3010/.well-known/openid-configuration}
      FEATURE_FLAG_PACKAGING_RECYCLING_NOTES_EXTERNAL_API: true
      FEATURE_FLAG_PACKAGING_RECYCLING_NOTES: true
      LOG_FORMAT: ecs


  epr-frontend:
    profiles: ['all', 'epr-frontend']
    environment:
      FEATURE_FLAG_PACKAGING_RECYCLING_NOTES: ${FEATURE_FLAG_PACKAGING_RECYCLING_NOTES:-true}
      WASTE_ORGANISATIONS_API_URL: http://waste-organisations-mock-api:3020/waste-organisations/organisations
      WASTE_ORGANISATIONS_API_USERNAME: testuser
      WASTE_ORGANISATIONS_API_PASSWORD: testpassword

  epr-admin-frontend:
    profiles: ['all', 'epr-admin-frontend']
    environment:
      ENTRA_CLIENT_ID: ${ENTRA_CLIENT_ID:-clientId}
      ENTRA_TENANT_ID: ${ENTRA_TENANT_ID:-tenantId}
      EPR_BACKEND_URL: http://epr-backend:3001
      OIDC_WELL_KNOWN_CONFIGURATION_URL: ${ENTRA_OIDC_WELL_KNOWN_CONFIGURATION_URL:-http://entra-stub:3010/.well-known/openid-configuration}
    networks:
      - cdp-tenant
