{
 "title": "epr-backend (epr-re-ex-service)",
 "description": "Overview of epr-re-ex-service\n\nCovers backend and two UIs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "User journey KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UploadSummaryLog",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "journey": "UploadSummaryLogStart" },
     "label": "Started",
     "metricName": "TransactionStart",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "journey": "UploadSummaryLogEnd" },
     "label": "Finished",
     "metricName": "TransactionEnd",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SaveDraftPRN",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "journey": "SaveDraftPRNStart" },
     "label": "Started",
     "metricName": "TransactionStart",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "journey": "SaveDraftPRNEnd" },
     "label": "Finished",
     "metricName": "TransactionEnd",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "IssuePRN",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "journey": "IssuePRNStart" },
     "label": "Started",
     "metricName": "TransactionStart",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "journey": "IssuePRNEnd" },
     "label": "Finished",
     "metricName": "TransactionEnd",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DiscardPRN",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "journey": "DiscardPRNStart" },
     "label": "Started",
     "metricName": "TransactionStart",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "journey": "DiscardPRNEnd" },
     "label": "Finished",
     "metricName": "TransactionEnd",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DeletePRN",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "journey": "DeletePRNStart" },
     "label": "Started",
     "metricName": "TransactionStart",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "journey": "DeletePRNEnd" },
     "label": "Finished",
     "metricName": "TransactionEnd",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CancelPRN",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "journey": "CancelPRNStart" },
     "label": "Started",
     "metricName": "TransactionStart",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "journey": "CancelPRNEnd" },
     "label": "Finished",
     "metricName": "TransactionEnd",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SaveDraftReport",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "journey": "SaveDraftReportStart" },
     "label": "Started",
     "metricName": "TransactionStart",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "journey": "SaveDraftReportEnd" },
     "label": "Finished",
     "metricName": "TransactionEnd",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SubmitReport",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "journey": "SubmitReportStart" },
     "label": "Started",
     "metricName": "TransactionStart",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "journey": "SubmitReportEnd" },
     "label": "Finished",
     "metricName": "TransactionEnd",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DeleteReport",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "journey": "DeleteReportStart" },
     "label": "Started",
     "metricName": "TransactionStart",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "journey": "DeleteReportEnd" },
     "label": "Finished",
     "metricName": "TransactionEnd",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "PRN Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "PRN Status Transitions",
   "type": "timeseries",
   "description": "Showing all status transitions for PRNs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "metricName": "prn.statusTransition",
     "metricQueryType": 1,
     "namespace": "epr-backend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "epr-backend", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "toStatus", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "prn.statusTransition", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(\"prn.statusTransition\") FROM \"epr-backend\" GROUP BY toStatus",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Status Transitions",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "prn.statusTransition",
     "metricQueryType": 1,
     "namespace": "epr-backend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "epr-backend", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "toStatus", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "prn.statusTransition", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"prn.statusTransition\") FROM \"epr-backend\" GROUP BY toStatus ORDER BY SUM() ASC",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Created PRNS by material",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "metricName": "prn.statusTransition",
     "metricQueryType": 1,
     "namespace": "epr-backend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "epr-backend", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "material", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "prn.statusTransition", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "awaiting_authorisation" }, "property": { "name": "toStatus", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(\"prn.statusTransition\") FROM \"epr-backend\" WHERE toStatus = 'awaiting_authorisation' GROUP BY material",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "December PRN's created  - by processor type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "metricName": "prn.created",
     "metricQueryType": 1,
     "namespace": "epr-backend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "epr-backend", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "processingType", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "prn.created", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "true" }, "property": { "name": "isDecemberWaste", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(\"prn.created\") FROM \"epr-backend\" WHERE isDecemberWaste = 'true' GROUP BY processingType",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "December PRNs — obligation year carried forward",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "dimensions": {
      "obligationYearCarriedForward": "true",
      "toStatus": "accepted"
     },
     "label": "PRN count",
     "metricName": "prn.statusTransition",
     "namespace": "epr-backend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Defra Forms submissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Defra Forms submissions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 48 },
   "targets": [
    {
     "alias": "Organisation",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/organisation\" AND method: POST AND status:200",
     "timeField": "@timestamp"
    },
    {
     "alias": "Organisation error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/organisation\" AND method: POST AND NOT status:200",
     "timeField": "@timestamp"
    },
    {
     "alias": "Registration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/registration\" AND method: POST AND status:201",
     "timeField": "@timestamp"
    },
    {
     "alias": "Registration error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/registration\" AND method: POST AND NOT status:201",
     "timeField": "@timestamp"
    },
    {
     "alias": "Accreditation",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/accreditation\" AND method: POST AND status:201",
     "timeField": "@timestamp"
    },
    {
     "alias": "Accreditation error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/accreditation\" AND method: POST AND NOT status:201",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Defra Forms submissions totals",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Organisation",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/organisation\" AND method: POST AND status:200",
     "timeField": "@timestamp"
    },
    {
     "alias": "Organisation error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/organisation\" AND method: POST AND NOT status:200",
     "timeField": "@timestamp"
    },
    {
     "alias": "Registration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/registration\" AND method: POST AND status:201",
     "timeField": "@timestamp"
    },
    {
     "alias": "Registration error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/registration\" AND method: POST AND NOT status:201",
     "timeField": "@timestamp"
    },
    {
     "alias": "Accreditation",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/accreditation\" AND method: POST AND status:201",
     "timeField": "@timestamp"
    },
    {
     "alias": "Accreditation error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/v1/apply/accreditation\" AND method: POST AND NOT status:201",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Operator Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Sign in/out traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "alias": "/login",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-frontend_ssl\" AND uri:\"login\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "/auth/callback",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-frontend_ssl\" AND uri:\"auth/callback\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "/logout",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-frontend_ssl\" AND uri:\"logout\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Operator sign in/out totals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "oidcProvider": "defra-id" },
     "label": "Sign in started",
     "metricName": "signInAttempted",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "oidcProvider": "defra-id" },
     "label": "Sign in complete",
     "metricName": "signInSuccess",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "oidcProvider": "defra-id" },
     "label": "Sign in complete - Non-initial Users",
     "metricName": "signInSuccessNonInitialUser",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "oidcProvider": "defra-id" },
     "label": "Sign in error",
     "metricName": "signInFailure",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "oidcProvider": "defra-id" },
     "label": "Sign out",
     "metricName": "signOutSuccess",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Organisations linked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "label": "Organisations linked",
     "metricName": "organisation.linked",
     "namespace": "epr-backend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Waste Records",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "operation": [ "*" ], "processingType": [ "*" ] },
     "metricName": "summaryLog.wasteRecords",
     "namespace": "epr-backend",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "processingType": "*" },
     "metricName": "summaryLog.decemberWasteRows",
     "namespace": "epr-backend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Summary Log submissions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "processingType": [ "*" ], "status": [ "submitted" ] },
     "metricName": "summaryLog.statusTransition",
     "namespace": "epr-backend",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Submission (p90)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "metricName": "summaryLog.submission.duration",
     "namespace": "epr-backend",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p90"
    }
   ]
  },
  {
   "title": "Validation (p90)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "metricName": "summaryLog.validation.duration",
     "namespace": "epr-backend",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p90"
    }
   ]
  },
  { "title": "Regulator activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Sign in/out traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "alias": "/regulators/login",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-frontend_ssl\" AND uri:\"regulators/login\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "/auth/callback/entra",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-frontend_ssl\" AND uri:\"auth/callback/entra\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "/logout",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-frontend_ssl\" AND uri:\"logout\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Regulator sign in/out totals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "oidcProvider": "entra-id" },
     "label": "Sign in started",
     "metricName": "signInAttempted",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "oidcProvider": "entra-id" },
     "label": "Sign in complete",
     "metricName": "signInSuccess",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "oidcProvider": "entra-id" },
     "label": "Sign in error",
     "metricName": "signInFailure",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "oidcProvider": "entra-id" },
     "label": "Sign out",
     "metricName": "signOutSuccess",
     "namespace": "epr-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Admin Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Sign in/out traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 81 },
   "targets": [
    {
     "alias": "/auth/sign-in",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-re-ex-admin-frontend_ssl\" AND uri:\"auth/sign-in\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "/auth/callback",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-re-ex-admin-frontend_ssl\" AND uri:\"auth/callback\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "/auth/sign-out",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-re-ex-admin-frontend_ssl\" AND uri:\"auth/sign-out\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Sign in/out totals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "label": "Sign in started",
     "metricName": "signInAttempted",
     "namespace": "epr-re-ex-admin-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "label": "Sign in complete",
     "metricName": "signInSuccess",
     "namespace": "epr-re-ex-admin-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "label": "Sign in error",
     "metricName": "signInFailure",
     "namespace": "epr-re-ex-admin-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "label": "Sign out",
     "metricName": "signOutSuccess",
     "namespace": "epr-re-ex-admin-frontend",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Organisation update",
   "type": "timeseries",
   "description": "Modifications to organisations",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 88 },
   "targets": [
    {
     "alias": "Success",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/organisations/\" AND method: PUT AND status:200",
     "timeField": "@timestamp"
    },
    {
     "alias": "Failure",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/organisations/\" AND method: PUT AND NOT status:200",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Organisation update totals",
   "type": "stat",
   "description": "Modifications to organisations",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Success",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/organisations/\" AND method: PUT AND status:200",
     "timeField": "@timestamp"
    },
    {
     "alias": "Failure",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"epr-backend_ssl\" AND uri: \"/organisations/\" AND method: PUT AND NOT status:200",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}