name: Renovate Docker

on:
  schedule:
    - cron: '0 2 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/renovate-docker
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
