name: Renovate Docker

on:
  schedule:
    - cron: '0 2 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/renovate-docker
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
